kind: PersistentVolume
apiVersion: v1
metadata:
  name: crate-vol
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data